apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchlabels:
      name: nginx-ingress
    template:
      metadata
        labela:
          name: nginx-ingress
      spec:
        containers:
          - name: nginx-ingress-controller
            ###put nginx ingress image here
            image:
        args:
          - /nginx-ingress-controller
          - --configmap=$(POD_NAME)/nginx-configuration
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        Ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
